services:
  - type: web
    name: gradesworld-backend
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: PYTHON_VERSION
        value: 3.10
      - key: DATABASE_URL
        fromDatabase:
          name: gradesworld-db
          property: connectionString
      - key: SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: False
      - key: RENDER
        value: True

databases:
  - name: gradesworld-db
    plan: free
